services:
  backend:
    build:
      context: ./  # This points to the current directory where your backend Dockerfile is located
    ports:
      - "8080:8080"
    env_file:
      - .env  # Path to the backend environment file, assuming it is in the root of `civil-affairs-backend`
    depends_on:
      - mongo
    networks:
      - app-network  

  frontend:
    build:
      context: ./decision-tree-editor  # Path to the frontend (React app) Dockerfile
    ports:
      - "3000:3000"  # React Dev Server runs on port 3000
    env_file:
      - ./decision-tree-editor/.env
    depends_on:
      - backend  # Ensure backend is available before frontend starts
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network 


  nginx:
    image: nginx:latest  # Using the latest Nginx image
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration
    ports:
      - "80:80"  # Exposing Nginx on port 80 (the default HTTP port)
    depends_on:
      - frontend
      - backend
    networks:
      - app-network 

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
